### ISSUE TITLE
Illegal division by zero at gibcounter.pl line 120.

### ISSUE THREAD

**Issue by hurburd** [creaktive/GibCounter#1]
hi,

gibcounter runs a little bit, but exits with this message:

Processing...
Illegal division by zero at gibcounter.pl line 120.

any idea what i can do?

thx!

**Comment by creaktive** [comment]
Sorry it took me about 6 years to react... So, apparently, every player must die at least once in the history of the Quake log file; otherwise this bug is caused. Sorry somehow back then I thought it would be an impossible situation :)
